version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: 0.0.0.0:5000
  headers:
    X-Content-Type-Options: [nosniff]
  tls:
    certificate: /certs/cert.pem
    key: /certs/key.pem
    clientcas:
      - /certs/ca.pem
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3