apiVersion: v1
kind: Service
metadata:
  name: registry-port
  labels:
    name: registry-port
spec:
  type: NodePort
  ports:
    - port: 5000
      nodePort: 30500
      targetPort: 5000
      name: http
    - port: 443
      nodePort: 32443
      targetPort: 443
      name: https
  externalIPs:
    - 10.11.1.71
    - 10.11.1.72
    - 10.11.1.73
  selector:
    name: my-registry