apiVersion: v1
kind: Service
metadata:
  name: zuul-service
spec:
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    io.kompose.service: zuul
  type: LoadBalancer